### PR TITLE
Added Support for Belgian Smartmeter types Sagemcom T211& S211

### PR DESCRIPTION
**Pull request by begunrom**
Hi,

I added support for the Belgian smartmeters. In flanders alse the current voltage and current are read by the meter.

### CODE REVIEW

**Comment by philipp90** [comment]
Hi @begunrom,

I know this question is a bit off topic, but where did you find/get the parameters (baudrate, databits, etc.) for this smart meter?

I've got the [Sagemcom T211-D](https://www.sagemcom.com/V02/smart-city/smart-meter/electricity/plc-power-line-carrier/plc-t210-three-phase/) some months ago but did not find any useful information.
May I try your parameters, if I have some free time - perhaps they will also work for mine.

**Comment by begunrom** [comment]
Hi philipp90,

The Sagemcom T211 parameters will also work for you.
Most new devices use 115200, no parity, 1 stop bit.

**Comment by Spoker** [comment]
Just installed a loxberry just for this. Can't wait for it to be merged 👍

**Comment by philipp90** [comment]
> Hi philipp90,
> 
> The Sagemcom T211 parameters will also work for you.
> Most new devices use 115200, no parity, 1 stop bit.
> 
> Please note that in the current released version the baud rate in the program is 115300. This is a bug i fixed as well in this commit.

Thanks for your reply!
Unfortunately it didn't work for me.
But maybe I'm making another mistake: Are you using P1 interface? I'm currently using the IR interface, since I've used it for my previous power meter (Iskra MT174).

**Comment by begunrom** [comment]
I am using the P1 interface.

**Comment by begunrom** [comment]
As i heard that many Belgians were waiting for it, i created a tag, so you can download the new version easily. Please be aware that Michael is planning a major rewrite of thi splugin, so this addition might never make it into the distribution.
https://github.com/begunrom/LoxBerry-Plugin-Smartmeter/releases/tag/Smartmeter-V1.1.5

**Comment by triples12** [comment]
Is there a way to see the usage of the gas meter? Fluvius told me that the gas meter is communicating with the sagecom but can't find the parameters of it.

**Comment by blacksun80** [comment]
@begunrom , thankx for your support. merge complete to master.

**Pull request merged**
